version: '3'

services:
 app_graph:
   build:
     context: .
   ports:
     - "8000:8000"
   volumes:
     - ./src:/src
   command: >
     sh -c "python manage.py wait_for_db &&
         python manage.py migrate &&
         python manage.py runserver 0.0.0.0:8000"
   environment:
    - DB_HOST=dbapp
    - DB_NAME=graphenedb
    - DB_USER=postgres
    - DB_PASS=supersecretpassword
   depends_on:
    - dbgraph
    

 dbgraph:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=graphenedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
